#server:
#  port: 5000
#  servlet:
#    encoding:
#      charset: utf-8

#spring:
#  thymeleaf:
#    prefix: "classpath:/templates/"
#    suffix: ".html"
#    cache: false

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${rds.hostname}:${rds.port}/${rds.db.name}
#    username: ${rds.username}
#    password: ${rds.password}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://codechefdb.czywaum4cloy.ap-northeast-2.rds.amazonaws.com/codechefdb
    username: codechef
    password: codechef1234

  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
#      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

aws:
  s3:
    bucket: codechef
    access-key: ${ACCESS}
    secret-key: ${SECRET}
    region: ap-northeast-2


